### ISSUE TITLE
Dot.Notation name as key & default value for get()

### ISSUE THREAD

**Issue by TemaSM** [UniSharp/laravel-settings#3]
**Explanation:**
If I have never called `Setting::set('my.setting', true);` and wanna retrieve value with default like this: `Setting::get('my.setting', false);`, that will return me not `false` as expected, but `null`.
Issue goes away if I stop using _dot.notation_ for key name and default value works as a charm.
**Examples:**
`Setting::get('my_setting', false);` - gives me `false` as default if there is no `mysetting`
`Setting::get('my.setting', false);` - gives me `null` as default if there is no `mysetting`, but hey WTF?

**Comment by AEK-BKF** [comment]
I confirm it :+1:
